[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "groupsandsets"
version = "0.1"
dependencies = ["numpy"]

[tool.hatch.build]
# Include both packages (groups and sets)
packages = ["groups", "sets"]
